# One gate row -> one check script. Deterministic.
# -v NAME= -v N= -v COND= -v REFUSAL= -v STEP= -v TABLE= -v OUT= -v WANT=
#
# Two kinds of gate come out of here, and the difference is the whole argument
# for decision tables:
#
#   a PROSE condition   -> a stub. Somebody must implement it, and until they do
#                          the check refuses everything and says so.
#   a TABLE condition   -> a working check. The table is the logic, it was
#                          checked for arity and overlap by V35-V39, and a
#                          reviewer who cannot read bash can still read it.
END {
  if (TABLE != "") { emit_decision_check(); exit }
  print "#!/usr/bin/env bash"
  print "# Generated by the formula compiler for " NAME ", gate " N "."
  print "#"
  print "# THE CONDITION, from the design:"
  print "#   " COND
  print "#"
  print "# THE REFUSAL, from the design:"
  print "#   " REFUSAL
  print "#"
  print "# Exit 0   the condition is satisfied; the step closes."
  print "# Exit 1   not yet. Consumes an attempt, and the refusal above is the message."
  print "# Exit 75  the check COULD NOT RUN — a missing service, an unreadable file."
  print "#          It does not consume an attempt. Never use it for a business failure."
  print "set -euo pipefail"
  print ""
  print "UNIT=\"${1:-}\"    # which unit this is, for the message"
  print "VALUE=\"${2:-}\"   # the value the condition compares"
  print ""
  print "# A real check reads what it needs from the unit record or from configuration."
  print "# VALUE is a convenience for a single-threshold gate; it is never model output."
  print ""
  print "# ---------------------------------------------------------------------------"
  print "# IMPLEMENT THE CONDITION HERE."
  print "#"
  print "# It is a condition, so it ends in a comparison. Read the numbers from the"
  print "# unit or from config — never from the model's own output."
  print "# ---------------------------------------------------------------------------"
  print ""
  print "echo \"REFUSED: " REFUSAL "\" >&2"
  print "echo \"         This check is not implemented. " NAME " gate " N ".\" >&2"
  print "exit 1"
}

function emit_decision_check() {
  print "#!/usr/bin/env bash"
  print "# Generated by the formula compiler for " NAME ", gate " N "."
  print "#"
  print "# THE CONDITION, from the design:"
  print "#   " COND
  print "#"
  print "# THE REFUSAL, from the design:"
  print "#   " REFUSAL
  print "#"
  print "# This one is NOT a stub. The condition names decision table \"" TABLE "\","
  print "# which is in the design, was checked for arity and overlap before this was"
  print "# written, and is evaluated below. The table is the logic; this is plumbing."
  print "#"
  print "# Exit 0   the table did NOT yield " OUT "=" WANT "; the step closes."
  print "# Exit 1   it did. The refusal above is the message."
  print "# Exit 75  the check COULD NOT RUN — the table is missing, or the inputs are."
  print "set -uo pipefail"
  print "HERE=$(cd \"$(dirname \"$0\")\" && pwd)"
  print "TSV=\"$HERE/../decisions/" TABLE ".tsv\""
  print "[ -f \"$TSV\" ] || { echo \"REFUSED: no decision table at $TSV.\" >&2; exit 75; }"
  print ""
  print "UNIT=\"${1:-}\"    # which unit this is, for the message"
  print "shift 2>/dev/null || true"
  print "# The table says which inputs it takes, in order. Pass them after the unit."
  print "[ $# -gt 0 ] || { awk -F\"\\t\" \x27/^#inputs/{printf \"REFUSED: this gate needs:\"; for(i=2;i<=NF;i++) printf \" %s\", $i; print \"\"}\x27 \"$TSV\" >&2; exit 75; }"
  print ""
  print "set +e"
  print "GOT=$(awk -v IN=\"$(printf \x27%s\\037\x27 \"$@\" | sed \x27s/.$//\x27)\" \\"
  print "        -f \"$HERE/../lib/dt-cell.awk\" -f \"$HERE/../lib/decide.awk\" \"$TSV\" 2>&1)"
  print "RC=$?"
  print "set -e"
  print "# 75 passes straight through: the table could not be evaluated, which is"
  print "# infrastructure and must never read as a business failure."
  print "[ \"$RC\" != 75 ] || { echo \"$GOT\" >&2; exit 75; }"
  print "# A fall-through is a case nobody decided. That is not a pass."
  print "if [ \"$RC\" = 1 ]; then"
  print "  echo \"$GOT\" >&2"
  print "  echo \"REFUSED: " REFUSAL "\" >&2"
  print "  exit 1"
  print "fi"
  print ""
  print "# Which column is " OUT "?  Read it from the table, never hard-coded here:"
  print "# the emitter and the table would drift the first time a column moved."
  print "COL=$(awk -F\"\\t\" \x27/^#outputs/{for(i=2;i<=NF;i++) if ($i==\"" OUT "\") {print i-1; exit}}\x27 \"$TSV\")"
  print "[ -n \"$COL\" ] || { echo \"REFUSED: " TABLE " has no output " OUT ".\" >&2; exit 75; }"
  print "VAL=$(printf \x27%s\x27 \"$GOT\" | cut -f\"$COL\")"
  print ""
  print "if [ \"$VAL\" = \"" WANT "\" ]; then"
  print "  echo \"REFUSED: " REFUSAL "\" >&2"
  print "  echo \"         " TABLE " yielded " OUT "=$VAL for unit ${UNIT:-?}.\" >&2"
  print "  exit 1"
  print "fi"
  print "exit 0"
}
