# design -> Mermaid flowchart, colored by step type. The second view of the same design.
function clean(t, n,   s) {
  s=t; gsub(/[;#"]/," ",s); gsub(/[\r\n]/," ",s); gsub(/\|/,"/",s); gsub(/[()\[\]{}]/,"",s)
  gsub(/^[ \t]+|[ \t]+$/,"",s); gsub(/[ \t][ \t]+/," ",s)
  if (n>0 && length(s)>n) s=substr(s,1,n-1) "…"
  return s
}
END {
  print "%% Generated by render.sh from the design. Do not edit by hand."
  print "flowchart TB"
  print "    IN([\"" clean(V["meta.use_case"],70) "\"]):::io"
  prev="IN"
  for (i=1;i<=s;i++) {
    t=tolower(STYPE[i]); id="S" SID[i]
    lbl="<b>" toupper(clean(SNAME[i],24)) "</b><br/>" clean(SDESC[i],64) "<br/><i>" t " · " tolower(SACT[i]) "</i>"
    isgate=0; for (j=1;j<=g;j++) if (GAFT[j]==SID[i]) isgate=1
    if (t=="gate" && isgate) {
      for (j=1;j<=g;j++) if (GAFT[j]==SID[i]) {
        SEENG[j]=1; print "    " id "{\"<b>GATE</b><br/>" clean(GCOND[j],56) "\"}:::gate"
        print "    " prev " --> " id
        print "    " id " -- refuses --> H" j "([\"" clean(GREF[j],72) "\"]):::out"
        print "    H" j ":::out"
        prev=id; break }
    } else {
      cls = (t=="mechanical" ? "mech" : t=="thinking" ? "think" : t=="test" ? "test" : t=="gate" ? "gate" : "coord")
      print "    " id "[\"" lbl "\"]:::" cls
      print "    " prev " --> " id
      prev=id
      for (j=1;j<=g;j++) if (GAFT[j]==SID[i]) {
        SEENG[j]=1; print "    G" j "{\"<b>GATE</b><br/>" clean(GCOND[j],56) "\"}:::gate"
        print "    " prev " --> G" j
        print "    G" j " -- refuses --> H" j "([\"" clean(GREF[j],72) "\"]):::out"
        prev="G" j }
    }
  }
  miss=""
  for (j=1;j<=g;j++) if (!(j in SEENG)) miss=miss " " j
  if (miss!="") {
    print "render.sh: gate(s)" miss " name a step id that does not exist — nothing rendered" > "/dev/stderr"
    exit 1
  }
  print "    " prev " --> OUT([\"DELIVER to " clean(V["meta.approver"],40) "<br/>the machine never approves its own work\"]):::out"
  print "    classDef mech fill:#d6ead6,stroke:#3a7d3a"
  print "    classDef coord fill:#e9e3d2,stroke:#7a6a3a"
  print "    classDef think fill:#f5dbe4,stroke:#8f3754"
  print "    classDef test fill:#dceef5,stroke:#2d6d80"
  print "    classDef gate fill:#f7e3b5,stroke:#9c7b1a"
  print "    classDef io fill:#eee,stroke:#555"
  print "    classDef out fill:#fff,stroke:#333"
}
