# design -> Mermaid sequence diagram. Deterministic: same design, same bytes.
function clean(t, n,   s) {
  s=t; gsub(/[;#]/," ",s); gsub(/[\r\n]/," ",s); gsub(/\|/,"/",s)
  gsub(/^[ \t]+|[ \t]+$/,"",s); gsub(/[ \t][ \t]+/," ",s)
  if (n>0 && length(s)>n) s=substr(s,1,n-1) "…"
  return s
}
function alias(t,   s) { s=t; gsub(/[();:#]/,"",s); gsub(/[ \t][ \t]+/," ",s); return s }
END {
  for (i=1;i<=s;i++) { t=tolower(STYPE[i]); a=tolower(SACT[i])
      if (t=="thinking" && a=="model") has_model=1
      if (t=="thinking" && a=="human") has_expert=1 }
  approver = (V["meta.approver"]!="" ? V["meta.approver"] : "a named approver")

  print "%% Generated by render.sh from the design. Do not edit by hand —"
  print "%% edit the design and render again. This diagram cannot disagree with it."
  print "sequenceDiagram"
  print "    autonumber"
  print "    participant C as Clock"
  print "    participant L as Loop"
  if (has_model)  print "    participant M as Model"
  if (has_expert) print "    participant X as Expert"
  print "    participant H as " alias(approver)
  print "    participant G as Ledger"
  print ""
  print "    Note over L,G: every transition below is appended to the ledger"
  print "    C->>L: tick — " clean(V["meta.use_case"],56)
  print ""

  for (i=1;i<=s;i++) {
    t=tolower(STYPE[i]); a=tolower(SACT[i])
    label = SID[i] " " clean(SNAME[i],24) " — " clean(SDESC[i],60)

    if (t=="gate") {
      rendered_as_gate=0
      for (j=1;j<=g;j++) if (GAFT[j]==SID[i]) { gate_block(j, label); rendered_as_gate=1 }
      if (!rendered_as_gate) print "    L->>L: " label " [gate condition not stated]"
      continue
    }

    # the step's own work
    if (t=="thinking" && a=="model") {
      print "    L->>M: " label
      print "    M-->>L: a call, with the evidence it cites"
    }
    else if (t=="thinking" && a=="human") {
      print "    L->>X: " label
      print "    X-->>L: a call, with the evidence they cite"
    }
    else if (i==s) {
      print "    L->>H: " label
      print "    L-)G: delivered"
      print "    Note over H: nothing is approved here. A named person approves it, or does not."
      print "    H-->>L: approved, or returned with a reason"
    }
    else print "    L->>L: " label

    # then any gate the design attaches to it — whatever kind of step it is. A design may
    # guard a judgment, a delivery or a selection, and the picture has to show it.
    for (j=1;j<=g;j++) if (GAFT[j]==SID[i]) gate_block(j, "")
  }

  # A control that was silently left out of the picture is the failure this course is about.
  miss=""
  for (j=1;j<=g;j++) if (!(j in RENDERED)) miss=miss " " j
  if (miss!="") {
    print "render.sh: gate(s)" miss " name a step id that does not exist — nothing rendered" > "/dev/stderr"
    exit 1
  }
}
function gate_block(j, label,   c,r) {
  RENDERED[j]=1
  c = clean(GCOND[j],72); r = clean(GREF[j],96)
  print "    alt " c
  print "        L->>H: REFUSE — " r
  print "        L-)G: refused"
  print "        Note over L,H: this unit stops here, with a named next action"
  print "    else the gate admits it"
  print "        L->>L: " (label!="" ? label : "proceed")
  print "    end"
}
