#!/usr/bin/env bash
# Bind a run's checks to its values, once, at the start of the run.
#
#   bind-checks.sh <artifact_root> <checks_dir> KEY=VALUE ...
#
# A formula declares [vars] at cook time. An exec check needs those values at run
# time, and gc passes it only GC_BEAD_ID. Recovering them at run time means a
# check that needs gc on PATH, a reachable bead store, a cwd inside a city tree
# and a login-shell environment — four dependencies, each of which failed at
# least once in the week of 2026-10-02, every time reporting something else.
#
# So bind them here instead. Each emitted wrapper exports its values literally
# and execs the real check. The result needs nothing but a filesystem, which is
# the same property emit-bundle.sh already gives the RPA it produces.
#
# Exit 0  every wrapper written and executable
# Exit 1  a named check is missing, so nothing was written
# Exit 64 wrong arguments
set -uo pipefail
R=${1:?artifact_root}; C=${2:?checks_dir}; shift 2
[ -d "$R" ] || { echo "no artifact_root at $R" >&2; exit 64; }
[ -d "$C" ] || { echo "no checks directory at $C" >&2; exit 64; }

# The checks a design-authoring run uses. A name here that is not in $C is a
# dropped gate, so it refuses rather than emitting a partial set.
CHECKS="design-reviewed design-validate design-audited diagrams-complete bundle-records prior-archived questions-asked questions-answered"

MISSING=""
for n in $CHECKS; do [ -f "$C/$n.sh" ] || MISSING="$MISSING $n"; done
[ -z "$MISSING" ] || { echo "REFUSED: these checks are not in $C:$MISSING" >&2
  echo "         Nothing was written. A missing check is a gate that would not run." >&2; exit 1; }

OUT="$R/checks"
mkdir -p "$OUT" || { echo "could not create $OUT" >&2; exit 1; }

# Build the export block once, quoting every value so a path with a space or a
# quote cannot change what the wrapper does.
EXPORTS=$(for kv in "$@"; do
  k=${kv%%=*}; v=${kv#*=}
  [ -n "$k" ] || continue
  printf "export %s='%s'\n" "$k" "$(printf '%s' "$v" | sed "s/'/'\\\\''/g")"
done)

for n in $CHECKS; do
  W="$OUT/$n.sh"
  {
    echo "#!/usr/bin/env bash"
    echo "# Generated by bind-checks.sh for this run. Do not edit."
    echo "# Every value below was known when the formula was cooked. Binding them"
    echo "# here means this check needs no gc, no bead store, no particular cwd and"
    echo "# no login-shell environment to find its own inputs."
    echo "set -uo pipefail"
    echo "$EXPORTS"
    printf "exec '%s' \"\$@\"\n" "$C/$n.sh"
  } > "$W"
  chmod +x "$W" || { echo "could not make $W executable" >&2; exit 1; }
done

echo "bound $(echo $CHECKS | wc -w | tr -d ' ') check(s) into $OUT, against $C"
echo "values: $(for kv in "$@"; do printf '%s ' "${kv%%=*}"; done)"
